In [45]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

In [46]:
df=pd.read_csv("mental_health_combined_test (1).csv")

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    992 non-null    object
 1   status  992 non-null    object
dtypes: object(2)
memory usage: 15.6+ KB

In [48]:
df['status'].value_counts()

status
Anxiety       248
Depression    248
Normal        248
Suicidal      248
Name: count, dtype: int64

In [49]:
df['status'].unique()

array(['Anxiety', 'Depression', 'Normal', 'Suicidal'], dtype=object)

In [50]:
df.isna().sum()

text      0
status    0
dtype: int64

In [51]:
df.drop_duplicates().sum()

text      i don't understand whats wrong with me. i don'...
status    AnxietyAnxietyAnxietyAnxietyAnxietyAnxietyAnxi...
dtype: object

In [52]:
df.isna().sum()

text      0
status    0
dtype: int64

In [53]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    return text

df['text'] = df['text'].apply(clean_text)

In [58]:
X = df['text']
y = df['status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [59]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [60]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_tfidf, y_train)

lr_pred = lr.predict(X_test_tfidf)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))
print(classification_report(y_test, lr_pred))

Logistic Regression Accuracy: 0.6432160804020101
              precision    recall  f1-score   support

     Anxiety       0.77      0.66      0.71        50
  Depression       0.55      0.55      0.55        49
      Normal       0.76      0.74      0.75        50
    Suicidal       0.53      0.62      0.57        50

    accuracy                           0.64       199
   macro avg       0.65      0.64      0.65       199
weighted avg       0.65      0.64      0.65       199

In [61]:
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

nb_pred = nb.predict(X_test_tfidf)

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print(classification_report(y_test, nb_pred))

Naive Bayes Accuracy: 0.5125628140703518
              precision    recall  f1-score   support

     Anxiety       0.61      0.70      0.65        50
  Depression       0.41      0.43      0.42        49
      Normal       0.91      0.20      0.33        50
    Suicidal       0.45      0.72      0.55        50

    accuracy                           0.51       199
   macro avg       0.60      0.51      0.49       199
weighted avg       0.60      0.51      0.49       199

In [62]:
svm = LinearSVC()
svm.fit(X_train_tfidf, y_train)

svm_pred = svm.predict(X_test_tfidf)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
print(classification_report(y_test, svm_pred))

SVM Accuracy: 0.5829145728643216
              precision    recall  f1-score   support

     Anxiety       0.69      0.68      0.69        50
  Depression       0.47      0.49      0.48        49
      Normal       0.70      0.66      0.68        50
    Suicidal       0.48      0.50      0.49        50

    accuracy                           0.58       199
   macro avg       0.59      0.58      0.58       199
weighted avg       0.59      0.58      0.58       199

In [68]:
def predict_mental_health(text):
    text = clean_text(text)
    vector = tfidf.transform([text])
    return svm.predict(vector)[0]

print(predict_mental_health("I am very feel bad and tesnion very good"))

Normal

In [71]:
import joblib

# Save trained model
joblib.dump(svm, "mental_health_model.pkl")

# Save TF-IDF vectorizer
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model aur Vectorizer successfully !")

Model aur Vectorizer successfully save ho gaye!